apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 labels:
  application: incident-logger
  component: frontend
spec:
 template:
  metadata:
   name: frontend
   labels:
    application: incident-logger
    component: frontend
  spec:
   containers:
   - name: frontend
     image: tenyedi96/incident-logger-frontend:latest
     ports:
      - containerPort: 80
        name: frontend
 replicas: 1
 selector:
  matchLabels:
   application: incident-logger
   component: frontend
