apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-logger.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incident-logger.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "incident-logger.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "incident-logger.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: api
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: backend
          env:
            - name: DB_HOST
              value: {{ include "incident-logger.fullname" . }}-mysql
            - name: DB_PORT
              value: "{{ .Values.mysql.service.port }}"
            - name: DB_USER
              value: {{ .Values.mysql.auth.username }}
            - name: DB_PASSWORD
              value: {{ .Values.mysql.auth.password }}
            - name: DB_NAME
              value: {{ .Values.mysql.auth.database }}
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}