apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incident-logger.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "incident-logger.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "incident-logger.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "incident-logger.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: http
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory }}
              cpu: {{ .Values.frontend.resources.limits.cpu }}
